### ISSUE TITLE
Vibration won't work without 'VIBRATE' permission for Android device

### ISSUE THREAD

**Issue by paulbao** [ideacreation/react-native-vibration#1]
Need to add below code into AndroidManifest.xml to make vibrating work.
`<uses-permission android:name="android.permission.VIBRATE" />`
And I think it's better to write this down in Readme file

**Comment by andreaskeller** [comment]
Thank you @paulbao for your input. @Nagle's merged pull request implements your suggestion. Therfor I close this issue.

**Comment by Noitidart** [comment]
Vibration isn't working for me on iOS either, is there a permission to add there?

**Comment by paulbao** [comment]
No, this lib only supports Android.

**Comment by Noitidart** [comment]
Oh! Thanks so much @paulbao  for your fast reply. I thougt I was posting on the official react native github. I was using this module - https://facebook.github.io/react-native/docs/vibration.html

Are you familiar with that?

**Comment by paulbao** [comment]
Can you paste your code here to see if there's something wrong?

**Comment by Noitidart** [comment]
Thank you so much for your offer sir!!

My code is this:

```
import React, { Component } from 'react'
import { Vibration, View, Text, Animated } from 'react-native'

  crash = () => {
    const { gameover, gameover_anim } = this.state;
    if (gameover) return;
    this.setState(()=>({gameover:true}));
    this.hole.stop();
    Animated.timing(gameover_anim, { toValue:1, duration:700, useNativeDriver:true }).start();
    console.log('you lose');
    Vibration.vibrate();
  }
```

The vibrate is happening on the last line. It works perfect on Android.

**Comment by paulbao** [comment]
Maybe try to add the pattern for it like:
```
const pattern = [0, 1000, 2000, 3000];
Vibration.vibrate(pattern, true);
```

**Comment by Noitidart** [comment]
Thanks very much for that @paulbao ! I tried it but it didn't work. :( It might be a bug on their side huh?

**Comment by paulbao** [comment]
Which RN version are you working with?

**Comment by Noitidart** [comment]
Excuse the delay please @paulbao I am using 0.44.2

Thanks again so much!

**Comment by paulbao** [comment]
Interesting, I just did the same test and it works for me. I'm running RN 0.44.

**Comment by Noitidart** [comment]
Oh wow my sincerest thanks for putting in that much effort @paulbao - 

I am on a iPad - maybe the vibrations are deactivated, I will check it out. If that is the case I am totally embarassed.

**Comment by paulbao** [comment]
You are welcome. That must be the case...I don't think iPad supports vibration.
